### PR TITLE
Add veto enable/disable at run time

### PR DESCRIPTION
**Pull request by FreddieAkeroyd**
Add PVs to enable and disable a veto at run time

See ISISComputingGroup/IBEX#1704

### CODE REVIEW

**Comment by FreddieAkeroyd** [comment]
Send the name "FIFO" for fifo veto

**Comment by DominicOram** [comment]
I'm not sure this is working. To test I'm setting `caput -S %MYPVPREFIX%DAE:VETO:DISABLE:SP FIFO` and checking whether the veto is enabled in the vetos panel within the GUI. After the caput it is still ENABLED, is this correct?

**Comment by FreddieAkeroyd** [comment]
It should go to DISABLED - there was a typo in the DB file, try again now

**Comment by FreddieAkeroyd** [comment]
If you add them all to python, i'll complete the relevant back end (only fifo works at the moment)

"FIFO" - fifo veto
"EXT0" - external veto 0
"EXT1" - external veto 1
"EXT2" - external veto 2
"EXT3" - external veto 3
"SMP" - SMP veto
"TS2P" - TS2 pulse veto
"ISIS50HZ" - ISIS not at 50Hz veto

**Pull request merged**
