### PR TITLE
Add reading of per period uah

### PR DESCRIPTION
**Pull request by FreddieAkeroyd**
See ISISComputingGroup/IBEX#8499

This PR also improves NORD readback behaviour

### CODE REVIEW

**Review by iangillingham-stfc — CHANGES_REQUESTED** [review]
image

**Comment by FreddieAkeroyd** [comment]
Hi, mine does this if there is a mismatch in ISISICP version or registration. Did you update ISISICP via `update_dev.bat` as per ISISComputingGroup/IBEX#8499  including doing the `register_server` as admin bit it mentions at the end?

**Comment by FreddieAkeroyd** [comment]
Actually, i've noticed that the admin register bit was commented out of `update_dev` as it didn't work at that point due to different paths, i've now fixed that so you should run `update_dev` again and this time there should be a register program to run. Registration only needs to be redone if a new function is added to the interface, last time that happened was three years ago so not very often

**Comment by iangillingham-stfc** [comment]
```
 C:\Instrument\Dev\ibex_bluesky_core :: 20_user_facing_dae                                   |  ibex_bluesky_core | 15:42:49
➜ caget TE:NDW2920:DAE:SPEC:0:1:XE.NORD
TE:NDW2920:DAE:SPEC:0:1:XE.NORD 50

 C:\Instrument\Dev\ibex_bluesky_core :: 20_user_facing_dae                                   |  ibex_bluesky_core | 15:43:00
➜ caget TE:NDW2920:DAE:SPEC:0:1:X.NORD
TE:NDW2920:DAE:SPEC:0:1:X.NORD 50
```

Shouldn't XE have size one more than X?

**Review by iangillingham-stfc — APPROVED** [review]

**Pull request merged**
