### PR TITLE
Add XE for bin edges

### PR DESCRIPTION
**Pull request by FreddieAkeroyd**
Add e.g. `SPEC:1:1:XE` to access bin edges

### CODE REVIEW

**Comment by Tom-Willemsen** [comment]
I thought `XE` should always have one more element than `X`? I got this after beginning and ending a run:

```
c:\Instrument\Apps\Python3>caget TE:NDW2922:DAE:SPEC:0:0:X.NORD
TE:NDW2922:DAE:SPEC:0:0:X.NORD 7995

c:\Instrument\Apps\Python3>caget TE:NDW2922:DAE:SPEC:0:0:XE.NORD
TE:NDW2922:DAE:SPEC:0:0:XE.NORD 8000
```

Maybe this would be a good use case for PVA instead of CA... then we should be able to serve arrays with dynamic size properly... I'm aware that's a bigger change though.

**Comment by FreddieAkeroyd** [comment]
Seems to work for me? Can i see your setup?

C:\Instrument\Apps\EPICS-DEBUG3\ioc\master\ISISDAE>caget TE:NDW2127:DAE:SPEC:0:0:XE.NORD
TE:NDW2127:DAE:SPEC:0:0:XE.NORD 101

C:\Instrument\Apps\EPICS-DEBUG3\ioc\master\ISISDAE>caget TE:NDW2127:DAE:SPEC:0:0:X.NORD
TE:NDW2127:DAE:SPEC:0:0:X.NORD 100

**Comment by FreddieAkeroyd** [comment]
Issue turns out to be related to how we were testing - NORD in ISISDAE PCAS is only updated when data is read i.e. reading "X" will name X.NORD be updated withing the program, just reading NORD after changing settings returns an old value. If the GUI is running, it might be reading a spectrum and hence NORD may look to be updating without a read.

I've fixed updating NORD without a read, but as i've had to add a new ISISICP function i combined this with the uamps ticket. So currently:
- if you review this ticket as is, it will work provided a read of data is done before a read of NORD
- if you review after #8499 has been merged, then NORD should update after a change of TCB in ibex GUI

**Comment by FreddieAkeroyd** [comment]
I am going to close this PR and merge the changes into the uamps branch, then i just need one set of tests

**Pull request closed without merging**
