### PR TITLE
If archiver fails to reload, force hard restart via procServ

### PR DESCRIPTION
**Pull request by FreddieAkeroyd**
See ISISComputingGroup/IBEX#2104

You also need to merge ISISComputingGroup/EPICS-ioc#135

To test:

# First check normal behaviour

* Start up ibex server
* Connect a console to the block archiver       console –M localhost ARBLOCK
* Begin a run – you should see the archiver restart in the console window, but no procserv messages (wait at least 10 seconds)
* Abort the run

# Check recovery behaviour

To do this you need to make a small edit, the program checks for RUNNING and restarts if that is not found, so change the check to look for something other than RUNNING and it should test the hard restart part

* Edit support/isisdae/db/isisdae.db   and change  the word “RUNNING” to say “xRUNNING” in the xpath PV (note: we are editing  the generated file so do not type make again)
* Restart the DAE IOC so it reloads above file 
* Begin a run – you should first see the restart message as before, then after about 5 seconds you should see procserv messages indicating a process restart as "xRUNNING" isnot found on the archiver web status page

### CODE REVIEW

**Comment by Tom-Willemsen** [comment]
I did the steps as above but couldn't see a difference when I put "xRUNNING" into the xpath in the following file `C:\Instrument\Apps\EPICS\support\isisdae\master\db\isisdae.db`, line 1168.

I searched my entire logs directory for "xRUNNING" but no hits. Is there something obvious I'm missing?

**Comment by FreddieAkeroyd** [comment]
If you edited master\db\isisdae.db and then restarted the IOC that should be enough, you should then additionally get procServ restart messages in the ARBLOCK console but I assume you are only seeing java messages? You need procServControl IOC running, which should be the case after a start_ibex_server

**Comment by FreddieAkeroyd** [comment]
You will not find xRUNNING in any ioc log - the change means the IOC will look for xRUNNING on the web page, which it will never find, so should then go onto a restart via procServ

**Comment by Tom-Willemsen** [comment]
Sorry, it was just my lack of understanding of the distinction between soft/hard restarts.

**Comment by FreddieAkeroyd** [comment]
No problem, thanks for reviewing it

**Pull request merged**
